calliope/core.py

when using 'verbose' it creates a more useful set of logging points and saves them to the main model as a dictionary element 'run_times' for later checking.

Added more runtime logging points

---

calliope/core.py

Few old lines weren't removed on merge during Pull #15 for some reason, just updating that error.

Patch merge error in runtime logging

---

.travis.yml
calliope/analysis.py
calliope/constraints/base.py
calliope/core.py
calliope/test/test_model_conversion.py

Fix for issue #50, including an additional test. Not merging directly as it's worth checking that it makes sense and covers the issue fully.

Update max and min prod constraints

---

calliope/time_masks.py

Fix time masking when set_t.csv contains sub-hourly resolutions

---

calliope/cli.py
changelog.rst
doc/_static/github-ribbon.html
doc/index.rst
requirements/base.yml
setup.py

* Docs: add GitHub ribbon to index page 
* CLI: use ipython debugger instead of built-in pdb 
~~- [ ] Test(s) added to cover contribution~~

Cosmetic fixes

---

calliope/config/model.yaml
calliope/core/preprocess/checks.py

* ``required_constraints`` must also be ``allowed_constraints``

required_constraints must also be allowed_constraints

---

calliope/config/defaults.yaml
calliope/config/model.yaml

~~- [ ] Test(s) added to cover contribution~~
~~- [ ] Changelog updated~~

Alphabetically sort `model` and `defaults` config YAML files

---

calliope/backend/pyomo/constraints/dispatch.py
calliope/test/test_example_models.py
changelog.rst

Fix storage_inter_cluster failing when no storage techs are defined

---

.appveyor.yml
.travis.yml
calliope/core/attrdict.py
calliope/core/model.py
calliope/core/preprocess/locations.py
calliope/test/test_core_attrdict.py
requirements/base.yml
requirements/dev_tools.yml
requirements/docs.yml
requirements/latest.yml
requirements/travis.yml
setup.py

Fixes issue(s) #139 
* Update ruamel.yaml to 0.15.71
* Remove comment passthrough to simplify AttrDict
* Add python 3.7 to travis tests
* No longer list anaconda channel in requirements

Modernise dependencies and add Py3.7 test

---

calliope/test/test_core_preprocess.py
changelog.rst
doc/user/ref_advanced_func.rst
doc/user/ref_config_listing.rst

Abstract base tech groups can be amended. To me, that wasn't clear from the documentation, so I updated the doc and wrote a test.

Fix documentation on amendments of abstract base tech groups

---

doc/user/analysing.rst
doc/user/ref_advanced_func.rst
doc/user/ref_config_listing.rst

Fixes issue(s) #
* Some updates and corrections in the docs
~~- [ ] Test(s) added to cover contribution~~
~~- [ ] Changelog updated~~
~~- [ ] Coverage maintained or improved~~

Doc updates

---

calliope/backend/pyomo/constraints/group.py
calliope/config/defaults.yaml
calliope/test/common/test_model/energy_cap.yaml
calliope/test/test_constraint_results.py
changelog.rst
doc/user/ref_advanced_func.rst

Feature energy cap constraint

---

calliope/core/preprocess/checks.py
calliope/core/preprocess/constraint_sets.py
calliope/core/preprocess/model_data.py
calliope/core/preprocess/sets.py
calliope/test/common/test_model/demand_share.yaml
calliope/test/common/test_model/group_constraints.yaml
calliope/test/test_backend_pyomo.py
calliope/test/test_constraint_results.py
doc/user/ref_advanced_func.rst

Implements https://github.com/calliope-project/calliope/issues/199.
* allow group constraints to be switched off in scenarios

Add option to switch off group constraints

---

calliope/backend/pyomo/constraints/group.py
calliope/config/defaults.yaml
calliope/test/common/test_model/energy_cap_share.yaml
calliope/test/test_constraint_results.py
changelog.rst
doc/user/ref_advanced_func.rst

Feature energy cap share contraint

---

calliope/backend/pyomo/constraints/group.py
calliope/config/defaults.yaml
calliope/test/common/test_model/resource_area.yaml
calliope/test/test_constraint_results.py
changelog.rst
doc/user/ref_advanced_func.rst

Feature resource area group constraint

---

calliope/config/defaults.yaml
calliope/core/preprocess/checks.py
calliope/test/test_core_preprocess.py
changelog.rst

Fixes issue(s) #207.
* Unknown top level tech parameters stop execution with an error message.

Fix unknown tech parameters

---

calliope/core/preprocess/time.py
calliope/test/test_core_time.py
changelog.rst

Fixes issue(s) #165
* Catch mismatch exceptions and print out the offending file, column, and loc::tech for easier user debugging.
* Add test to ensure exception is raised.
* Update changelog.

Add column mismatch error capture; add tests; update changelog

---

calliope/backend/pyomo/constraints/capacity.py
calliope/config/defaults.yaml
calliope/core/preprocess/checks.py
calliope/core/preprocess/constraint_sets.py
calliope/test/common/test_model/energy_cap.yaml
calliope/test/common/test_model/energy_cap_share.yaml
calliope/test/common/test_model/group_constraints.yaml
calliope/test/common/test_model/model.yaml
calliope/test/common/test_model/model_cost_cap.yaml
calliope/test/common/test_model/resource_area.yaml
calliope/test/common/test_model/supply_share.yaml
calliope/test/test_backend_pyomo.py
calliope/test/test_constraint_results.py
calliope/test/test_core_preprocess.py

After running the changes of #223 manually, I found it was broken. 😬 Here's a fix.

Fix the names of the new constraints

---

calliope/backend/pyomo/constraints/group.py
calliope/test/common/test_model/demand_share.yaml
calliope/test/test_constraint_results.py

Fixes issue(s) #227 
~- [ ] Changelog updated~

Fix demand share group constraint

---

calliope/analysis/postprocess.py
calliope/test/common/test_model/energy_cap_per_storage_cap.yaml
calliope/test/test_example_models.py
changelog.rst

Fixes issue(s) #210 
Use only supply all technologies when calculating the total lcoe.

Fix total lcoe

---

calliope/__init__.py
calliope/analysis/postprocess.py
calliope/backend/pyomo/constraints/group.py
calliope/backend/pyomo/interface.py
calliope/backend/pyomo/model.py
calliope/backend/pyomo/util.py
calliope/backend/run.py
calliope/cli.py
calliope/core/__init__.py
calliope/core/attrdict.py
calliope/core/model.py
calliope/core/preprocess/checks.py
calliope/core/preprocess/model_run.py
calliope/core/time/funcs.py
calliope/core/util/logging.py
calliope/test/test_backend_pyomo.py
calliope/test/test_cli.py
calliope/test/test_core_util.py
changelog.rst
doc/api/api.rst
doc/user/running.rst

Fixes issue(s) #226
* Revised logging and warnings

Warn and log

---

calliope/backend/pyomo/constraints/group.py
calliope/core/preprocess/model_data.py
changelog.rst

* Group constraint values are parameters

Group constraint values are parameters

---

calliope/analysis/postprocess.py
calliope/backend/pyomo/interface.py
calliope/backend/pyomo/model.py
calliope/backend/run.py
calliope/core/model.py
calliope/core/time/clustering.py
calliope/core/time/funcs.py
calliope/test/test_backend_pyomo.py
calliope/test/test_backend_pyomo_interface.py
calliope/test/test_backend_pyomo_objective.py
changelog.rst

* `model.backend.rerun` returns a calliope model
* More rigorous tests for the backend interface

Update backend interface

---

calliope/core/io.py
calliope/test/test_io.py

* Fix saving to netcdf after reading from netcdf

Fix saving to netcdf after reading from netcdf

---

calliope/config/defaults.yaml
calliope/core/preprocess/checks.py
calliope/test/common/test_model/model_config_group/base_model.yaml
calliope/test/common/test_model/model_config_group/scenarios_add_techs.yaml
calliope/test/common/test_model/model_config_group/scenarios_energy_cap.yaml
calliope/test/common/test_model/model_config_group/scenarios_energy_cap_share.yaml
calliope/test/common/test_model/model_config_group/scenarios_metadata.yaml
calliope/test/common/test_model/model_config_group/scenarios_resource_area.yaml
calliope/test/common/util.py
calliope/test/test_backend_pyomo_constraints_group.py

Partially fixes issue(s) #259
* Added resource area constraint tests

Add resource area group constraint tests

---

.appveyor.yml

* Try to get Appveyor working again by giving conda a helping hand

Try to get conda to not blow itself up

---

calliope/backend/pyomo/constraints/group.py
calliope/config/defaults.yaml
calliope/test/common/test_model/model_config_group/base_model.yaml
calliope/test/common/test_model/model_config_group/scenarios_net_import_share.yaml
calliope/test/test_backend_pyomo_constraints_group.py
changelog.rst
doc/user/advanced_constraints.rst

Fixes issue(s) #270 
* add a new constraint constraining net imports

Add net import share contraints

---

calliope/backend/pyomo/interface.py
calliope/test/test_backend_pyomo_interface.py
changelog.rst
doc/user/advanced_constraints.rst

Fixes issue(s) #294
* New Pyomo backend interface to add a custom constraint
* New Pyomo backend interface to view the variables, parameters, and sets in the existing backend model

New pyomo backend interface methods

---

.gitignore
calliope/backend/pyomo/constraints/dispatch.py
calliope/backend/pyomo/constraints/energy_balance.py
calliope/backend/pyomo/model.py
calliope/backend/pyomo/util.py
calliope/test/test_backend_pyomo.py
changelog.rst
requirements.txt
requirements.yml
setup.py

Fixes issue(s) #318
* Update `.gitignore`
* Update to Pyomo 5.7
* Clean up requirements more generally, including removal of the pandas dependencies `bottleneck` and `numexpr`

Pyomo update

---

doc/conf.py

Fix docs build

---

calliope/backend/pyomo/constraints/costs.py
calliope/backend/pyomo/constraints/group.py
calliope/backend/pyomo/util.py
calliope/test/test_backend_pyomo.py
calliope/test/test_backend_pyomo_util.py
changelog.rst

Fixes issue(s) #316 
* Catch when production costs are being applied to a transmission technology that can't produce energy
* Test
~~Documentation updated~~

Fix one way om costs

---

calliope/backend/pyomo/constraints/group.py

Internal helper func not in docs

---

doc/user/advanced_features.rst
doc/user/building.rst

* Mention SPORES in 'building a model' and 'advanced functionality' sections
* Point to Joule paper in which it is implemented

Add info on SPORES in docs

---

calliope/core/model.py
calliope/postprocess/plotting/__init__.py
calliope/postprocess/plotting/capacity.py
calliope/postprocess/plotting/flows.py
calliope/postprocess/plotting/plotting.py
calliope/postprocess/plotting/timeseries.py
calliope/postprocess/plotting/transmission.py
calliope/postprocess/plotting/util.py
changelog.rst
requirements.txt
requirements.yml

* Add plotting functionality back in as a calliope model object method
* Add warning that this functionality is going to go for good, and it is now untested

Reimplement plotting

---

.azure-pipelines.yml

This extends the triggers for PRs and branch-based CI to minimise the amount of testing being done. Only changes to those files which are part of the python package (and the few top-level test config files) should cause the test pipeline to run.

Add non-test relevant files to exclude path list

---

requirements.txt
requirements.yml

Equivalent to #403, but for v0.6.x

Add upper bounds for all v0.6.x dependencies

---

.azure-pipelines.yml

Codecov bot has stopped weighing in on PRs, this should hopefully fix that.
~Following advice of: https://devblogs.microsoft.com/devops/uploading-to-codecov-just-got-easier/~ <- EDIT: deprecated.
Following: https://docs.codecov.com/docs/codecov-uploader

Update azure pipelines config codecov upload

---

calliope/backend/checks.py
calliope/backend/pyomo/constraints/capacity.py
calliope/backend/pyomo/constraints/milp.py
calliope/backend/run.py
calliope/cli.py
calliope/core/util/generate_runs.py
calliope/postprocess/plotting/flows.py
calliope/postprocess/plotting/plotting.py
calliope/postprocess/plotting/timeseries.py
calliope/preprocess/checks.py
calliope/preprocess/locations.py
calliope/preprocess/model_run.py
calliope/preprocess/time.py
calliope/test/test_backend_pyomo.py
calliope/test/test_backend_pyomo_constraints_conversion_plus.py
calliope/test/test_backend_pyomo_constraints_group.py
calliope/test/test_backend_pyomo_interface.py
calliope/test/test_backend_pyomo_util.py
calliope/test/test_constraint_results.py
calliope/test/test_core_preprocess.py
calliope/test/test_core_util.py
calliope/test/test_example_models.py
calliope/test/test_io.py
calliope/time/clustering.py
calliope/time/masks.py
conftest.py

A simple restructure of where basic test models are generated and run to reduce duplication (and associated increase in runtime) in tests.

Speed up tests with session scope models on 0.6

---

calliope/test/common/lp_files/resource_max.lp
calliope/test/common/test_model/scenarios.yaml
calliope/test/test_math.py

* Add `resource_max` constraint test

Add resource_max constraint test

---

calliope/test/common/lp_files/balance_conversion.lp
calliope/test/test_math.py

Fixes issue(s) #
* Adds a test and the LP file to compare to.

Add test for constraint 'balance conversion'

---

calliope/test/common/lp_files/carrier_production_max.lp
calliope/test/test_math.py

* Added a test for the ` carrier_production_max` constraint

Add test carrier production max

---

calliope/core/model.py

Just added some missing docstrings and fixed a function giving general info on the model.

Model class cleanup: fix `info` & remove empty method; add docstrings.

---

.pre-commit-config.yaml
CHANGELOG.md
doc/_themes/flask_calliope/static/flasky.css_t
doc/user/develop.rst
doc/user/troubleshooting.rst
doc/user/tutorials_01_national.rst
doc/user/tutorials_02_urban.rst
pyproject.toml
src/calliope/backend/expression_parser.py
src/calliope/config/math_schema.yaml
src/calliope/core/model.py
src/calliope/exceptions.py
src/calliope/postprocess/postprocess.py
src/calliope/preprocess/time.py
tests/test_backend_expression_parser.py
tests/test_core_preprocess.py

Fixes #88 
* Add `codespell` pre-commit hook.
* Check spelling to have the hook pass (we weren't doing too badly).
Not spell checking Jupyter Notebooks due to [this issue](https://github.com/codespell-project/codespell/issues/2138).
- ~[ ] Test(s) added to cover contribution~
- ~[ ] Documentation updated~
- ~[ ] Changelog updated~

Add spell checking; fix spelling mistakes

---

.readthedocs.yml
doc/helpers/generate_plots.py
doc/helpers/generate_tables.py

* Updates readthedocs config to version 2 so 0.6 docs still build

Update readthedocs config on 0.6 branch

---

.github/workflows/release.yml

Protect PyPI upload with CI environment

---

CHANGELOG.md
docs/advanced/shadow_prices.md
docs/hooks/changelog_highlight.py
docs/migrating.md

Clean up changelog

---

CHANGELOG.md
src/calliope/_version.py

l https://pypi.org/simple calliope==0.7.0.dev3`)

Release v0.7.0.dev3

---

docs/installation.md

Fixes #579
* Improve installation instructions
* Add `glpk` to recommended installation one-liner so at least one solver is always installed

Improve installation instructions

---

CHANGELOG.md
docs/creating/data_sources.md
docs/examples/loading_tabular_data.py
docs/hooks/dummy_model/model.yaml
docs/migrating.md
docs/user_defined_math/syntax.md
src/calliope/config/data_source_schema.yaml
src/calliope/example_models/urban_scale/model.yaml
src/calliope/preprocess/data_sources.py
tests/common/national_scale_from_data_sources/model.yaml
tests/common/test_model/model.yaml
tests/common/test_model/scenarios.yaml
tests/test_math.py
tests/test_preprocess_data_sources.py
tests/test_preprocess_time.py

Rename dimensions to dims in docs

---

docs/creating/scenarios.md
docs/running.md
src/calliope/config/math_schema.yaml
src/calliope/config/model_def_schema.yaml

Update refs to `model.subset_time` & `run.objective`

---

src/calliope/backend/backend_model.py
src/calliope/backend/expression_parser.py
src/calliope/backend/helper_functions.py
src/calliope/backend/latex_backend_model.py
src/calliope/backend/parsing.py
src/calliope/backend/pyomo_backend_model.py
src/calliope/exceptions.py
src/calliope/model.py
src/calliope/preprocess/data_sources.py
src/calliope/preprocess/load.py
src/calliope/preprocess/model_data.py
src/calliope/util/logging.py
src/calliope/util/schema.py

Improves #631
* Updates docstrings affected by that PR.

docstring updates

---

src/calliope/backend/__init__.py
src/calliope/backend/backend_model.py
src/calliope/backend/helper_functions.py
src/calliope/backend/latex_backend_model.py
src/calliope/backend/parsing.py
src/calliope/backend/pyomo_backend_model.py
src/calliope/model.py
tests/common/util.py
tests/test_backend_module.py

Fixes #624
* The backend is now a module that shares only what is necessary to `model.py`.
* Backend fetching is now a `match-case` function. We can add new backends as needed.
* Invalid backend requests now return a clear error.

Improved backend maintainability 

---

docs/advanced/time.md
docs/creating/config.md
docs/migrating.md

Adds a simple example of how to use a third-party library (`tsam`) to generate a valid clustering timeseries file. Since I went through the process myself, I thought it would be worthwhile to add to the docs.
~- [ ] Test(s) added to cover contribution~
~- [ ] Changelog updated~
~- [ ] Coverage maintained or improved~

Add tsam clustering example

---

src/calliope/backend/backend_model.py

Fixes slow decision variable creation (noticed on building a larger model)

Remove array copy

---

CHANGELOG.md
docs/hooks/generate_readable_schema.py
docs/reference/api/attrdict.md
docs/reference/api/backend_model.md
docs/reference/api/example_models.md
docs/reference/api/exceptions.md
docs/reference/api/helper_functions.md
docs/reference/api/logging.md
docs/reference/api/model.md
docs/reference/api/schema.md
docs/reference/cli.md
mkdocs.yml

Fixes #670 
* De-ranked API (0.5) / schema (0.25) docs 
* Added search suggestions, sharing, and result highlighting, since we can.

De-boost reference docs; add search gadgets

---

docs/contributing.md

Fixes #720
* Small update to our docs to allow us to test the documentation locally.

Add missing kernel command in development instructions.

---

.github/workflows/commit-ci.yml
.github/workflows/pr-ci.yml
CHANGELOG.md
src/calliope/_version.py
src/calliope/backend/__init__.py
src/calliope/backend/gurobi_backend_model.py
tests/test_backend_general.py
tests/test_backend_pyomo.py
tests/test_example_models.py

I'd like to get this iteration through so we have access to the minor fixes required to make our new lower bound pinning work, and to access the SPORES algorithm in some projects.
Param & dim config will need to wait for the next iteration.

Release v0.7.0.dev6

---

CHANGELOG.md
docs/analysing.md
docs/creating/techs.md
docs/reference/api/postprocess.md
mkdocs.yml
requirements/base.txt
src/calliope/postprocess/postprocess.py

Fixes #767 
Fixes #762 
* Account for time resolution in timeseries capacity factor calc
* Account for export flow in levelised cost calc
* Add some docs on the postprocessing methods we use to generate the new datasets a user will see

Update postprocessing funcs

---

CHANGELOG.md
docs/examples/piecewise_constraints.py
docs/user_defined_math/examples/annual_energy_balance.yaml
docs/user_defined_math/examples/chp_htp.yaml
docs/user_defined_math/examples/demand_share_per_timestep_decision.yaml
docs/user_defined_math/examples/fuel_dist.yaml
docs/user_defined_math/examples/max_time_varying.yaml
docs/user_defined_math/examples/net_import_share.yaml
docs/user_defined_math/examples/piecewise_linear_costs.yaml
docs/user_defined_math/examples/share_all_timesteps.yaml
docs/user_defined_math/examples/share_per_timestep.yaml
docs/user_defined_math/examples/sos2_piecewise_linear_costs.yaml
src/calliope/math/base.yaml
src/calliope/math/milp.yaml
src/calliope/math/operate.yaml
src/calliope/math/spores.yaml
src/calliope/math/storage_inter_cluster.yaml
tests/test_backend_general.py

Update all YAML definitions with units and defaults
