calliope-project/calliope

- calliope/analysis.py
- calliope/analysis_utils.py
`.values()` is incorrect for DataArrays, so have updated to `to_pandas()` as with other DataArrays in analysis. Also added node labelling, as it is currently unknown which node is which when plotted.
Would be good to have node label background, so labels aren't obscured by edges, but `newtorkx.draw_networkx_labels` doesn't have that functionality it seems.
> Patch plot transmission

- calliope/config/defaults.yaml
- calliope/constraints/base.py
- calliope/utils.py
The technology doesn't retain distance information, so the previous line `distance = model.get_option(y + '.distance')` would always lead to an exception, leading to cost per distance always being 0. This has been updated along with more checks to ensure everything else is caught along the way. Could do with being generally cleaner, but it works in this format.
> Per distance patch

- calliope/config/defaults.yaml
- calliope/constraints/base.py
- calliope/core.py
- calliope/sets.py
- calliope/test/test_model_export.py
Currently it is possible to include export, by creating a demand technology with some big M demand and `force_r` set to false. However, you then have to define a new carrier for that export, to ensure only certain technologies are allowed to export (those that can produce this proxy carrier). 
This patch allows you to set `techs.[technology].export` to true for any technology you would like to have export some of its production outside the grid. `techs.[technology].revenue.[cost_type].sub_export` can then be set for that technology & given cost type to allow export to produce revenue.
Export energy is taken away *before* es_prod (i.e. technology production = es_prod + export), I think I've sorted any issues this may cause with costing and system balancing, but that might need more …
> Make exporting energy simpler to include

- calliope/analysis_utils.py
- calliope/core.py
- calliope/example_models/national_scale/model_config/locations.yaml
- calliope/example_models/urban_scale/model_config/locations.yaml
- calliope/test/test_analysis.py
Metadata can be supplied as lat-lon, and is then plotted with Basemap background. But, if you want a quick 'abstract' model (i.e. not geographically located, but there are distinct locations with distances between them) you can define as x-y. This allows for that.
Also updates metadata map boundary to be `[lat1, lon1, lat2, lon2]` instead of `[lon1, lat1, lon2, lat2]` to be in line with the definition of the other location lat-lons (i.e. `[lat, lon]`). For cartesian, this becomes [x1, y1, x2, y2], but isn't actually used at the moment.
> Update map plotting for x-y and lat-lon

- calliope/backend/pyomo/constraints/conversion_plus.py
- calliope/config/conversion_0.6.0.yaml
- calliope/config/defaults.yaml
- calliope/core/preprocess/checks.py
- calliope/core/preprocess/locations.py
- calliope/core/preprocess/lookup.py
- calliope/core/preprocess/model_run.py
- calliope/core/util/tools.py
- calliope/example_models/urban_scale/model_config/techs.yaml
- calliope/test/common/test_model/model.yaml
- calliope/test/test_backend_pyomo.py
- calliope/test/test_core_preprocess.py
- changelog.rst
- doc/user/ref_advanced_func.rst
- doc/user/whatsnew.rst
Separate `primary_carrier` into `primary_carrier_in`/`_out` for conversion_plus techs, to allow `om_con` and `om_prod` costs
* If a conversion_plus tech has multiple input/output carriers, the use can define the `primary_carrier_in` / `primary_carrier_out` to correctly assign costs. Previously, there was only `primary_carrier`, which referred to output carriers only
* Fixed variable cost constraint for conversion plus to look for `primary_carrier_in` when adding om_con costs
> Separate `primary_carrier` into `primary_carrier_in`/`_out`

- calliope/backend/pyomo/constraints/milp.py
- calliope/config/defaults.yaml
- calliope/config/model.yaml
- calliope/core/preprocess/constraint_sets.py
- calliope/core/preprocess/locations.py
- calliope/test/test_backend_pyomo.py
- changelog.rst
``units_max_systemwide`` and ``units_equals_systemwide`` can be applied to an integer/binary constrained technology (capacity limited by ``units`` not ``energy_cap``, or has an associated ``purchase`` (binary) cost). Constraint works similarly to existing ``energy_cap_max_systemwide``, limiting the number of units of a technology that can be purchased across all locations in the model.
> Add unit_capacity_systemwide_constraint

- calliope/core/model.py
- calliope/core/preprocess/checks.py
- calliope/core/preprocess/time.py
Update to un-reviewed commit d7e92f6429f15588415922b9765847ba6d9b5e0e
This PR moves the FutureWarning to a specific function, where all similar warnings should then be placed in future.
~~- [ ] Test(s) added to cover contribution~~ see d7e92f6429f15588415922b9765847ba6d9b5e0e
~~- [ ] Changelog updated~~  see d7e92f6429f15588415922b9765847ba6d9b5e0e
> Update where we store & check for FutureWarnings and DeprecationWarnings

- calliope/backend/pyomo/constraints/capacity.py
- calliope/backend/pyomo/constraints/milp.py
- calliope/core/preprocess/model_data.py
- calliope/test/test_backend_pyomo.py
- calliope/test/test_constraint_results.py
- changelog.rst
* If multiple technologies call the same systemwide constraint, the model won't break
* If a transmission technology calls a systemwide constraint, the systemwide constraint won't silently fail
> Fix systemwide constraints to include transmission techs

- calliope/analysis/postprocess.py
- calliope/backend/pyomo/constraints/energy_balance.py
- calliope/backend/pyomo/objective.py
- calliope/backend/pyomo/variables.py
- calliope/test/test_constraint_results.py
- changelog.rst
* System can be balanced due to forced excess supply, by the same mechanism as we currently handle unmet demand. 
* `excess_supply` decision variable is merged into `unmet_demand` on completion, leading to just the one data variable in `model.results`. However, it's possible for `unmet_demand` to be negative (i.e. excess supply).
> Add `excess_supply` variable when ensuring feasibility

- calliope/core/preprocess/locations.py
- calliope/test/test_core_preprocess.py
- changelog.rst
Fixes issue(s) #113 
* If only interest rate is defined for a cost class, resulting empty keys will be deleted before building the xarray dataset.
> Fix only interest rate defined in a cost class

- calliope/core/preprocess/model_run.py
- calliope/test/test_example_models.py
- changelog.rst
- doc/user/building.rst
- doc/user/ref_advanced_func.rst
- doc/user/tutorials_01_national.rst
Calliope needs at least one time series otherwise the model preprocess failed with unspecific error messages.
Now there is a check that at least one time series exists and the preprocess fails gracefully with a specific error message in case none exists.
> Fix assert time series

- calliope/config/defaults.yaml
- changelog.rst
* Fix default value of resource_area_max
Default was ``False`` with the intention to deactive the constraint. Quite the opposite actually happened: ``False`` was evaluated to ``0`` _activating_ this constraint to its full extent.
Now the default is ``inf`` which will actually deactive the constraint (in compliance with other upper bound constraints).
* made the documentation more generic
> Fix resource area max default

- calliope/cli.py
- calliope/core/preprocess/model_run.py
- calliope/example_models/national_scale/scenarios.yaml
- calliope/test/common/html_strings.yaml
- calliope/test/test_cli.py
- calliope/test/test_core_preprocess.py
- changelog.rst
- doc/user/building.rst
* Define scenarios in YAML as list, not string
> Define scenarios in YAML as list, not string

- calliope/backend/pyomo/constraints/capacity.py
- calliope/backend/pyomo/constraints/conversion.py
- calliope/backend/pyomo/constraints/conversion_plus.py
- calliope/backend/pyomo/constraints/dispatch.py
- calliope/backend/pyomo/constraints/energy_balance.py
- calliope/backend/pyomo/constraints/export.py
- calliope/backend/pyomo/constraints/milp.py
- calliope/backend/pyomo/objective.py
- calliope/backend/pyomo/variables.py
- calliope/test/common/html_strings.yaml
- calliope/test/common/test_model/model_minimal.yaml
- calliope/test/common/util.py
* Changed a HTML text entry in plotly tests to deal with plotly 3.5.0
* Updated some constraint math to avoid some escape sequence warnings
> Fix plotly test and some deprecation warnings

- calliope/backend/pyomo/constraints/capacity.py
- calliope/backend/pyomo/constraints/milp.py
- calliope/test/test_backend_pyomo.py
- changelog.rst
Fixes issue(s) #157
* Changed expectation for there to be transmission technologies when defining systemwide constraints
> Fixed systemwide constraint when modelling without transmission

- calliope/core/util/dataset.py
- calliope/test/test_core_util.py
- changelog.rst
> Fix retain data_var name in get_formatted_array

- calliope/cli.py
- calliope/test/test_cli.py
- changelog.rst
This is a breaking change.
This fixes https://github.com/calliope-project/calliope/issues/182.
Fixes issue(s) #182 
> Change exit code to no success when infeasible

- pytest.ini
* Ignore DeprecationWarnings of Pyomo during pytest execution.
> Ignore pyomo deprecation warnings during test

- calliope/backend/pyomo/constraints/group.py
- calliope/core/preprocess/model_data.py
- calliope/core/preprocess/sets.py
- calliope/test/common/test_model/model_demand_share.yaml
- calliope/test/test_backend_pyomo.py
- calliope/test/test_constraint_results.py
Fixes issue(s) #201 
* Group constraints stored in model_data with dimensions specific to those constraints. E.g. 'group_demand_share_min' is built over the dimension 'group_names_demand_share_min'.
* More tests to handle multiple group constraints being defined and multiple carriers at once.
> Update group name definition

- .appveyor.yml
- calliope/backend/pyomo/model.py
- calliope/config/model.yaml
- calliope/example_models/national_scale/model.yaml
- calliope/example_models/national_scale/scenarios.yaml
- calliope/example_models/urban_scale/model.yaml
- calliope/test/common/test_model/model.yaml
- calliope/test/common/test_model/model_demand_share.yaml
- calliope/test/common/test_model/model_minimal.yaml
- calliope/test/model_conversion/national_scale/run.yaml
- calliope/test/test_constraint_results.py
- calliope/test/test_example_models.py
- calliope/test/test_objective.py
- changelog.rst
- doc/user/installation.rst
Fixes issue(s) #204 
* Update Appveyor install instructions such that CBC can be installed on Windows.
* Update docs to inform users on how to install CBC on their OS (conda forge for all but Windows).
* Update example and models to default to CBC as the solver.
NOTE: I'm not certain the Windows install instructions are correct, since I don't have access to a Windows machine to check... All I remember is that the CBC instructions for Windows don't work out of the box.
> Set default solver to CBC

- calliope/core/preprocess/locations.py
- calliope/test/test_core_preprocess.py
- changelog.rst
Fixes issue(s) #190
* per loc::tech check for `locations[loc].techs[tech].costs[cost] is None` 
* warning and deletion of offending cost class
* Added test
> Checks and tests to warn on empty cost class

- calliope/core/preprocess/checks.py
- calliope/test/test_core_preprocess.py
- changelog.rst
Partially fixes issue(s) #198
* Check for defined techs/locs in group constraints that don't exist elsewhere in the model definition
* Remove those inexistent techs from the definition of the constraint in `model_data` and warn the user that it has happened, in case it was a misspelling.
> Remove inexistent locations/techs from group constraints

- calliope/core/preprocess/checks.py
- calliope/test/test_core_preprocess.py
- changelog.rst
Fixes issue(s) #215 
* Find instances of technologies defined in both directions of a link (e.g. `A,B` and `B,A`) and raise exception if they exist. Ignore instances of links being defined twice, but with different technologies.
> Raise exception when technology defined twice on the same link

- calliope/core/preprocess/locations.py
- calliope/test/test_core_preprocess.py
- changelog.rst
Partially fixes issue(s) #166
* If a link should be `A,B` but is defined as `A, B`, the space is stripped early on in preprocessing
* Test to check this
> Fix spaces in link names

- calliope/core/io.py
- calliope/core/model.py
- calliope/test/test_io.py
- changelog.rst
Fixes issue(s) #245
* Let model_run and debug data roundtrip through NetCDF
There seems to be no immediate limit on the size of strings in NetCDF attributes -- a test with a 20 MB large string did not reveal any performance or other issues (except that it adds 20 MB to the size of the resulting NetCDF file).
> Let model_run and debug data roundtrip through NetCDF

- calliope/config/defaults.yaml
Fixes issue(s) related to the recently allowed om_con cost for demand techs. In fact, also group constraint defaults need to be updated to allow generic and variable costs group constraints for demand techs.
Otherwise, demand variable costs will be allowed in general but, if a cost group constraint is defined, checks in the preprocess will exclude demand costs from the cost group constraint and raise a warning.
* Added generic costs and variable costs to group constraints allowed by demand techs
* Existing tests should cover this change already
*
> Fix warning demand cost

- calliope/backend/pyomo/model.py
- calliope/test/test_backend_pyomo.py
Fixes #272 (a regression introduced in #248)
* add a test for double logging with Gurobi
* mute Gurobi's direct stdout logging
While I think it's totally fine to mute Gurobi's direct stdout printing and rely on their additional logging (why do they do both?), this solution is not consistent with other loggers. This way, Gurobi logs will be INFO level rather than DEBUG level.
> Fix double logging when using Gurobi

- calliope/backend/pyomo/constraints/costs.py
- calliope/config/defaults.yaml
- changelog.rst
Fixes issue(s) #
* Fixed investment costs appearing with confusing (and used-elsewhere) name
* Fixed changelog reporting outdated name for storage_discharge_depth
* Fixed transmission techs not allowing 'energy_cap_min' without a reason 
> Fixes minor issues

- .azure-pipelines.yml
- calliope/analysis/postprocess.py
- calliope/core/time/funcs.py
- calliope/core/util/observed_dict.py
- calliope/test/test_analysis.py
- calliope/test/test_core_attrdict.py
- calliope/test/test_example_models.py
- changelog.rst
- codecov.yml
- pytest.ini
- requirements/base.yml
- requirements/dev_tools.yml
- setup.py
Updates for Python 3.8 compatibility
* Update dependencies for Python 3.8 on conda-forge
* Move pytest-xdist to base requirements and parallelise tests on Azure
* Requires changes to clustering example model tests due to a [fix in scikit-learn 0.22](https://scikit-learn.org/stable/whats_new/v0.22.html#sklearn-cluster) changing the behaviour of kmeans with a given random seed
> Updates for Python 3.8 compatibility

- calliope/config/defaults.yaml
Some per-tech constraints in the documentation had wrong or no unit specification
no unit specification:
- force_asynchronous_prod_con
- one_way
wrong unit specification:
- energy_cap_per_storage_cap_equals: was fraction -> now is h^-1
- resource_area_per_energy_cap: was boolean -> now is m^2/kW
Also I thought it's clearer to replace distance^-1 by fraction/distance for enegy_eff_per_distance and h^-1 by fraction/h for storage_loss
> fixed several units in per-tech constraints

- calliope/backend/checks.py
- calliope/backend/pyomo/constraints/group.py
- calliope/backend/pyomo/interface.py
- calliope/backend/pyomo/model.py
- calliope/backend/pyomo/util.py
- calliope/config/defaults.yaml
- calliope/test/test_backend_pyomo.py
- calliope/test/test_backend_pyomo_util.py
- changelog.rst
Fixes issue(s) #309 
* Pyomo `Param`objects are assigned a domain based on the variable dtype in `model_data`
* Domains now make it difficult to use None and np.nan as default values, so I've cleaned that up slightly
* Fixed an issue where updating values to `np.inf` in operate checks leads to large negative integer values if the variable`model_data` dtype is `int`. Those variables instead get assigned a float type.
> Fix pyomo param domain warnings

- calliope/core/attrdict.py
- calliope/preprocess/checks.py
- calliope/test/common/test_model/weighted_obj_func.yaml
- calliope/test/test_core_attrdict.py
- calliope/test/test_core_preprocess.py
- changelog.rst
Fixes issue(s) #300
* Fix silent override of nested dicts when parsing YAML
> Fix silent override of nested dicts when parsing YAML

- .azure-pipelines.yml
- doc/user/develop.rst
- doc/user/installation.rst
Additional fix for issue #378 
Having done some testing myself with different install methods, I have removed the pip-based recommendation (i.e., install an empty conva env then install calliope via pip within it). Some non-python binaries aren't installed and this can make saving to NetCDF fragile. In our conda-forge package we include them (`libnetcdf`, `hdf5`), but since they are not available via pip I would not recommend a user to install by this method. Of course, they could be referenced in the docs (i.e, install a conda env with just python and those non-python binaries) but since using `mamba` is a viable workaround on windows, it seems better to not muddy the waters.
I've also added an explicit python version in the dev docs since we are a bit behind the current Python version …
> Update install docs

- requirements.txt
- requirements.yml
Fixes issue of `click` being pinned in `requirements.txt` and not in `requirements.yml`.
> Update and align click between requirement files

- calliope/backend/pyomo/model.py
- calliope/backend/run.py
- calliope/preprocess/model_run.py
- calliope/test/test_backend_pyomo_interface.py
- calliope/test/test_backend_pyomo_objective.py
- calliope/test/test_cli.py
- calliope/test/test_core_preprocess.py
- calliope/test/test_example_models.py
- calliope/test/test_io.py
- pytest.ini
Some warnings are expected and ignored,
others are deprecation warnings from pytest itself.
> Reduce number of test warnings in 0.6.8-dev

- requirements.txt
- requirements.yml
Hotfixes issue(s) #402 (keep issue open until we've dealt with not trying to compress string/object arrays)
* Add strict minor version upper bound for libnetcdf
* Add strict minor version upper bound for netcdf4 so that it doesn't try to update libnetcdf in dev installs (where you install by updating with "requirement.yml" followed by "requirements.txt")
* Add the upcoming major releases for all required dependencies as an upper bound, in the hope of not being caught out by backward incompatible changes (although, in reality, they could crop up in minor releases).
> Add upper bounds to all v0.7 dependencies

- calliope/core/model.py
- changelog.rst
Fixes issue(s) #
* Remove obsolete `Model._datetime_to_string` context manager
> Fix: Remove obsolete _datetime_to_string context manager

- calliope/test/common/lp_files/energy_cap.lp
- calliope/test/common/util.py
- calliope/test/test_math.py
Fixes issue(s) #433 
* Add LP builder to test utils.
* Add example test for `energy_cap` decision variable and its bounds.
Following this PR, LP files for all base and custom math need to be created. This is quite a lot of manual work, but hopefully once done doesn't need to change again for a while.
> Add LP comparison pipeline and one example

- calliope/backend/parsing.py
- calliope/core/model.py
- calliope/math/base.yaml
- calliope/math/operate.yaml
- calliope/math/storage_inter_cluster.yaml
- calliope/test/common/util.py
- calliope/test/test_backend_pyomo.py
- calliope/test/test_core_model.py
- calliope/test/test_math.py
- calliope/test/test_parsing.py
Partially fixes issue(s) #418 
* Remove `equation: "..."` from math syntax and rely entirely on `equations: [{"expression": "..."}]`. More verbose, but easier to maintain and document.
> Remove references to `equation`

- .github/workflows/pr-ci.yml
Fixes sheer number of CI runners.
* macos and windows runners will only run on python version 3.11, while ubuntu tests older python versions.
> Only run py39 and py310 on ubuntu

- src/calliope/backend/pyomo_backend_model.py
- tests/common/lp_files/balance_conversion.lp
- tests/common/lp_files/carrier_production_max.lp
- tests/common/lp_files/resource_max.lp
- tests/common/lp_files/storage_max.lp
- tests/test_backend_pyomo.py
I realised that although I added the ability for variables and expressions to be verbose, I missed out constraints. They are useful if verbose in the LP files.
> Add ability to view constraint coords in LP files

- doc/user/advanced_constraints.rst
- doc/user/advanced_features.rst
- doc/user/tutorials_03_milp.rst
- src/calliope/backend/parsing.py
- src/calliope/backend/pyomo_backend_model.py
- src/calliope/config/defaults.yaml
- src/calliope/config/math_schema.yaml
- src/calliope/example_models/national_scale/scenarios.yaml
- src/calliope/math/base.yaml
- src/calliope/math/operate.yaml
- src/calliope/preprocess/checks.py
- tests/common/test_model/energy_cap_per_storage_cap.yaml
- tests/test_backend_parsing.py
- tests/test_backend_pyomo.py
- tests/test_core_preprocess.py
- tests/test_example_models.py
Fixes issue #422
* parameters defining a `_equals` variant removed in favour of using `_min` and `_max` simultaneously. For the most part this affects variable bounds, so will only increase model size if imposing `energy_cap_systemwide` or `units_systemwide` constraints, wherein two constraints are built instead of one. This is also not a massive issue since they are not built over the time dimensions so are unlikely to be particularly large constraint arrays
* scaling parameters `energy_cap_scale` and `resource_scale` parameters removed as they introduce a maintenance burden when we do not know of any cases of their actual use.
> Remove `_equals` and `_scale` parameters

- .github/workflows/commit-ci.yml
- .github/workflows/pr-ci.yml
- .readthedocs.yml
- README.md
- doc/user/introduction.rst
Fixes badges (I tried sneakily force pushing a minor change, but realised there's more to it)
* Update badges to work with current CI / apps
* Update badges to all rounded since some can't do flat-square styling
* Remove PDF generation of docs since the PDF build has been failing horribly for ~5 months (e.g. [here](https://readthedocs.org/projects/calliope/builds/22342627/))
> Update badges and remove pdf gen from rtd

- CHANGELOG.md
- src/calliope/config/config_schema.yaml
- src/calliope/config/model_def_schema.yaml
- src/calliope/preprocess/model_data.py
- tests/test_model_data.py
Fixes #209 
* `config.init.distance_unit` option available to define whether distances should be derived in metres or kilometres
> Add distance unit config item & default to km

- .github/workflows/commit-ci.yml
- .github/workflows/link-check.yml
- .github/workflows/pr-ci.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- README.md
- docs/installation.md
Fixes issue #520. 
Also added a link checker ~pre-commit hook~ GitHub CI action so that dead links will be caught in future.
It works on a weekly schedule and during pull requests.
EDIT: not using a pre-commit hook as the pre-commit CI doesn't have access to the network (see [here](https://github.com/pre-commit-ci/issues/issues/141)).
> Update links; add link checker

- src/calliope/backend/backend_model.py
- src/calliope/backend/latex_backend_model.py
- src/calliope/backend/pyomo_backend_model.py
Fixes issue found while implementing gurobi backend related to how updates to parameters filter through the rest of the backend model.
It now goes into variables and updates those if needs and it then implements the updates in order (parameters->variables->exprs->constrs->objective)
> Fix references between built backend components

- .github/workflows/pr-ci.yml
- mkdocs.yml
Fixes the release checklist so it's clickable. I find this useful for going through the checklist even if the checkboxes dont persist on refresh.
> Make release checklist clickable

- CHANGELOG.md
- src/calliope/_version.py
Let's try again!
l https://pypi.org/simple calliope==0.7.0.dev2`)
> Release v0.7.0.dev2

- docs/creating/config.md
- src/calliope/config/config_schema.yaml
- src/calliope/example_models/national_scale/model.yaml
- tests/common/test_model/energy_cap_per_storage_cap.yaml
- tests/common/test_model/model.yaml
- tests/common/test_model/model_minimal.yaml
- tests/common/test_model/weighted_obj_func.yaml
Fixes existence of `config.init.time_data_path` which no longer does anything. Thanks for noticing @irm-codebase.
> Purge `time_data_path`

- src/calliope/math/base.yaml
Equivalent fix to the issue raised in #565.
* Link `purchased_units` with `flow_cap` even when `flow_cap_max` has not been set by the user. Uses bigM to achieve this.
> Force link between flow cap and purchased units in base math

- CHANGELOG.md
- docs/reference/api/schema.md
- docs/user_defined_math/customise.md
- mkdocs.yml
- src/calliope/util/schema.py
- tests/test_core_util.py
Fixes issue of adding new parameters but not getting any of the benefits of having default data etc. stored in the model schema. This is useful for our separate pathways repo.
* Add schema updater for the model definition schema specifically.
* Add schema reset button to allow a user who has messed up their schema with weird things to return to a blank slate (would require a reload of Calliope otherwise).
> Add schema updater

- .github/workflows/commit-ci.yml
- .github/workflows/link-check.yml
- .github/workflows/pr-ci.yml
- .github/workflows/release.yml
- pyproject.toml
Codecov has been acting up so I think it's time to use their latest github action version and bite the bullet and add the CODECOV token to the repository secrets (they said it wasn't necessary for open source projects but uploads sometimes fail for lack of it).
Also updated a pyproject.toml setting that was wrong. Thanks @irm-codebase for picking up on that.
> Update CI action versions

- CHANGELOG.md
- docs/creating/data_sources.md
- src/calliope/preprocess/model_data.py
- tests/test_preprocess_model_data.py
Fixes #567 
* Always try to convert data dimensions to numeric and keep any successful attempts. 
* Add some tests.
* Add mention of this in the docs.
> Coerce model dimension dtypes to numeric

- requirements/dev.txt
It seems the [mkdocs 1.6](https://www.mkdocs.org/about/release-notes/#version-160-2024-04-20) breaks the builds.
* Pin mkdocs to < 1.6 to get docs building again
> Pin mkdocs to < 1.6 to get docs building again

- requirements/dev.txt
Fixes issue _not_ fixed in #591. There is curretnly a broken conda forge build on `mkdocs-jupyter`. See this [feedstock PR comment](https://github.com/conda-forge/mkdocs-jupyter-feedstock/pull/30#issuecomment-2088298861).
* Pin mkdocs-jupyter to < 0.24.7
> Pin to non-broken mkdocs-jupyter

- CHANGELOG.md
- docs/advanced/shadow_prices.md
- src/calliope/backend/backend_model.py
- src/calliope/backend/pyomo_backend_model.py
- src/calliope/config/config_schema.yaml
- src/calliope/model.py
- src/calliope/postprocess/postprocess.py
- tests/common/test_model/scenarios.yaml
- tests/test_backend_pyomo.py
Fixes #581
* Allow enabling shadow price tracking in YAML `config.solve`
* Only activate shadow price tracking if model is continuous and warn if it is not
* Improved tests for shadow price tracking
> Shadow price configuration in YAML

- CHANGELOG.md
- src/calliope/io.py
- src/calliope/model.py
Fixes #607
Just removed a parameter that is no longer used from the Calliope `__init__` function.
Also updated the docstring from v0.6 to 0.7
> Purge spurious debug parameter

- CHANGELOG.md
- src/calliope/backend/backend_model.py
- src/calliope/backend/pyomo_backend_model.py
- tests/common/test_model/model.yaml
- tests/test_backend_pyomo.py
#update
Fixes #616 
* Rebuild references in the order they appear in the backend model dataset, which is the same order they are added to it (so expressions that depend on previous expressions will be built in the correct order).
* Remove investment cost from demands in the dummy test model - this leads to a change in shadow prices which I have updated, but there's no way of knowing if the new shadow prices (or, indeed, the old ones) are correct.
* Force verbose strings on rebuilt backend model components, if verbose strings have already been triggered.
> Sort ref ordering within components

- CHANGELOG.md
- docs/user_defined_math/components.md
- src/calliope/backend/backend_model.py
- src/calliope/backend/latex_backend_model.py
- src/calliope/backend/parsing.py
- src/calliope/backend/pyomo_backend_model.py
- src/calliope/config/math_schema.yaml
- src/calliope/config/model_def_schema.yaml
- src/calliope/math/base.yaml
- src/calliope/math/storage_inter_cluster.yaml
- tests/conftest.py
- tests/test_backend_pyomo.py
- tests/test_core_model.py
Fixes #582 
Chosen "title" as it fits with the YAML/JSON schema syntax.
* Variables and global expressions get a "title" key that will be stored in the attributes of the result dataarrays
* Parameters already have a "title" key in the schema, this is also now passed to the attributes of the input dataarrays
> Add `title` to math var and expr components

- CHANGELOG.md
- src/calliope/io.py
- tests/test_io.py
Fixes #614
* single element lists / sets are logged and returned to being lists / sets on loading from NetCDF
> Add record of single element attribute lists in IO

- .github/workflows/commit-ci.yml
Fixes codecov not uploading successfully on `main` and its failure being silent. This is why we have failing coverage reports in all our PRs.
* Copy over codecov config from pr-ci to commit-ci.
> Fix: Update commit-ci codecov step

- CHANGELOG.md
- docs/examples/calliope_model_object.py
- src/calliope/model.py
- tests/test_core_preprocess.py
- tests/test_io.py
Part of #619
* Removes unused `model._model_def_dict` spam in xarray objects and saved data.
> Rework _model_def_dict

- mkdocs.yml
This should fix rendering of 404 error pages in the docs (see e.g. https://calliope.readthedocs.io/en/latest/foo)
> Fix rendering of 404 pages in the docs

- AUTHORS
- src/calliope/config/model_data_checks.yaml
- src/calliope/config/model_def_schema.yaml
- tests/test_backend_pyomo.py
Related to #643 
* Small fixes (typos, ...) to docstrings
* Checks for valid values of ~~`flow_cap_*` and~~ `storage_initial` (d99bf9451e4d0a1a7e26cf98bef28ea19d6132fb); ~~note that I'm unsure if the check for `flow_cap_min <= flow_cap_max` is done correctly?~~
> Fixes in docs and new data checks

- src/calliope/backend/backend_model.py
- src/calliope/backend/parsing.py
- src/calliope/preprocess/model_math.py
* Ordered math components (except for parameters) now live in `CalliopeMath`. Code now refers to them.
* Small comment fixes.
> PR improvements: math components in CalliopeMath, small fixes

- CHANGELOG.md
- src/calliope/backend/pyomo_backend_model.py
- src/calliope/math/base.yaml
- tests/common/lp_files/cost_var.lp
- tests/common/lp_files/cost_var_with_export.lp
- tests/common/util.py
- tests/test_math.py
Fixes #663 
* Checking for definition of `carrier_export` across all carriers
* Added LP comparison for the cost_var global expression
* Minor fixes to dtypes of backend components when checking their string implementation
> Fix multi carrier costs

- CHANGELOG.md
- src/calliope/config/model_def_schema.yaml
- src/calliope/math/base.yaml
Partial fix for #645. Just focussing on the _bug_ raised in that issue.
@sstroemer - can you check that I've got it right?
> Fix contribution of `cost_om_annual_investment_fraction` in math

- CHANGELOG.md
- docs/hooks/generate_math_docs.py
- docs/user_defined_math/customise.md
- src/calliope/backend/latex_backend_model.py
- tests/test_backend_latex_backend.py
Fixes #651
Fixes point 3 in #643 
* Added `Uses` which is the inverse of `Used in`
* Added collapsed admonitions for `Uses` and `Used in` when building math docs with mkdocs features enabled
* Explicitly removed self-references in `Uses` and `Used in`
> Add `uses` cross-ref to math docs & collapsed admonitions

- CHANGELOG.md
- src/calliope/config/model_def_schema.yaml
Fixes #653. 
* Re-word description of `flow_cap_min` to match suggestion by @sstroemer
> Update flow_cap_min description

- CHANGELOG.md
- src/calliope/backend/latex_backend_model.py
Fixes #652 
@sstroemer linking you here (I've now also invited you as a member of the org - I'll start asking for your reviews once you've accepted that invite!)
> Fix math docs var domain

- .github/workflows/commit-ci.yml
- .github/workflows/pr-ci.yml
Fixes failing tests seen in #690 
This is caused by latest micromamba updating to v2.0 and lots of issues arising. This one seems to have been flagged by someone else [here](https://github.com/mamba-org/micromamba-releases/issues/58)
* Pin to most recent v1 micromamba
> Pin micromamba version in CI

- CHANGELOG.md
- docs/creating/config.md
- docs/creating/parameters.md
- docs/examples/national_scale/index.md
- docs/examples/urban_scale/index.md
- docs/user_defined_math/syntax.md
- src/calliope/config/config_schema.yaml
- src/calliope/example_models/national_scale/data_tables/costs.csv
- src/calliope/example_models/national_scale/model.yaml
- src/calliope/example_models/national_scale/model_config/techs.yaml
- src/calliope/example_models/urban_scale/model.yaml
- src/calliope/example_models/urban_scale/model_config/techs.yaml
- src/calliope/preprocess/model_data.py
- tests/common/test_model/model.yaml
- tests/test_preprocess_model_data.py
Fixes #615 
* `config.init.broadcast_param_data` boolean option available as per suggestion from @irm-codebase. It defaults to False, so must be set knowingly by the user to True to allow for indexed parameter data broadcasting.
* Updated example models to use CSV cost data (national scale) and to have a top-level interest rate (since we don't change it per technology in our example models).
* Updated docs to include this info and reflect updates to example models.
> Add `broadcast_param_data` config option and default it to False.

- CHANGELOG.md
- docs/user_defined_math/helper_functions.md
- src/calliope/backend/helper_functions.py
- tests/conftest.py
- tests/test_backend_helper_functions.py
- tests/test_cli.py
- tests/test_core_util.py
Fixes #777
I had implemented these ad-hoc for other modelling efforts but since @fvandebeek brought it up in an issue I decided to formalise it in the core code.
The helper func names and docstrings might need more work to add clarity. I'd welcome ideas!
* `group_datetime` to sum over a time dimension in a math component using pre-defined datetime periods (date, hour, weekofyear, month, etc.)
* `sum_next_n` to apply a rolling summation over a time/ordered dimension of a math component.
> Add `group_datetime` and `sum_next_n` helper functions

- CHANGELOG.md
- docs/examples/piecewise_constraints.py
Based on discussion in #525
* Explicitly reference the new decision variable in the following global expression `where` string.
> Update piecewise cost expr in docs

- CHANGELOG.md
- docs/user_defined_math/helper_functions.md
- src/calliope/backend/helper_functions.py
- tests/test_backend_helper_functions.py
Fixes #735
On investigating #735, I realised that a generalisation of `group_datetime` introduced in #778 might be prudent. This was an option considered prior to implementing #698 but discounted as it was less intuitive. I'm bringing it back as a potential major memory saver when doing more complex multi-dimensional grouping. 
One option to consider here is to remove `group_datetime` entirely and point people to create an input array mapping their datetime dimension to relevant datetime periods (e.g. timesteps -> date) and then use `group_sum`.
* Added `group_sum` expression helper function
> Add `group_sum` helper function (potentially supersedes `group_datetime`)

- src/calliope/postprocess/postprocess.py
This solves a rare edge case: when making a single-node model where operate mode math is added to the base math and `flow_cap` is defined directly in-YAML, `cap_sum` ends up having no "nodes" dimension, leading to an exception in postprocessing.
> Postprocess: prevent exception when flow_cap lacks nodes dim

- CHANGELOG.md
- docs/hooks/clean_search.py
- mkdocs.yml
Fixes #675 
Mkdocs creates a search index JSON file which is what is used to fill the search results. I've gone to this source and removed/edited the notebook entries since they follow a similar pattern.
It's far from perfect since search results for entire code blocks (inputs and outputs) are lost as they are the same entry in the search index. However, it does keep the markdown parts of the notebooks, which is probably sufficient for useful search functionality.
I've also cleaned up how the search results are presented for rendered notebooks. For standard `.md` files, results are grouped under the top-level header. This wasn't the case for rendered notebooks as mkdocs doesn't seem to be able to understand that there is a top-level header. I've just said that the first header is the …
> Add hook to clean notebook pages in docs search index
